# Generated by Django 2.2.19 on 2021-07-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favicon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favicon',
            old_name='isFavicon',
            new_name='is_favicon',
        ),
    ]
